tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "yt-dlp/taps"
brew "archey"
brew "ffmpeg"
brew "figlet"
brew "fluid-synth"
brew "git"
brew "htop"
brew "node", link: false
brew "python@3.10"
brew "qemu"
brew "zsh"
brew "yt-dlp/taps/yt-dlp"
cask "cscreen"
cask "vscodium"
# extra stuff i added manually
cask "tiles"
cask "firefox"
cask "discord"
cask "telegram"
cask "spotify"
cask "foobar2000"